package com.ppzzl.learn.billling.model.common;

public enum ServState {
    NORMAL,
    CANCELED,
    CUSTOMER_SERVICE_SUSPENDED,
    INSUFFICIENT_BALANCE_SERVICE_SUSPENDED,
    CUSTOMER_INSUFFICIENT_BALANCE_SERVICE_SUSPENDED,
    ARCHIVED
}
